apiVersion: v1
kind: Service
metadata:
  name: flight-agent-service
spec:
  type: NodePort 
  selector:
    app: flight-agent 
  ports:
    - port: 7860       
      targetPort: 7860 
      nodePort: 30001  